#!/usr/bin/env python3
"""Regenerate typed localization accessors from the shared String Catalog."""
import json, re
from pathlib import Path
root = Path(__file__).resolve().parent.parent
catalog = root / 'ios/SharedResources/Localizable.xcstrings'
data = json.loads(catalog.read_text())
lines = ['// Generated by scripts/localize.py. Edit the String Catalog.', 'import Foundation', '', 'enum L10n {']
for key, entry in sorted(data['strings'].items()):
    if not re.fullmatch(r'[a-z][A-Za-z0-9]*', key): raise ValueError(key)
    for locale in ('en', 'nb'):
        unit = entry['localizations'][locale]['stringUnit']
        if unit['state'] != 'translated' or not unit['value']: raise ValueError((key, locale))
    lines.append(f'    static var {key}: LocalizedStringResource {{ LocalizedStringResource("{key}", table: "Localizable") }}')
lines.append('}')
(root / 'ios/Shared/L10n.swift').write_text('\n'.join(lines)+'\n')
uses = set()
for file in (root / 'ios').rglob('*.swift'):
    if file.name != 'L10n.swift': uses.update(re.findall(r'L10n\.([A-Za-z0-9]+)', file.read_text()))
missing = uses - data['strings'].keys()
if missing: raise ValueError(f'Missing localizations: {missing}')
print(f'Validated {len(data["strings"])} English and Norwegian strings; generated typed accessors.')
